### ISSUE TITLE
Roadmap for v0.2.0

### ISSUE THREAD

**Issue by lomirus** [lomirus/gtk-qq#7]
- [x] Load, cache and show avatars
- [x] Save login account and password
- [x] Cache the friends list and groups list
- [ ] ~~Save chats history~~ (Delayed, may in v0.3.0 or later)
- [x] Push notification when receiving message
- [ ] ~~Add unread badge for chat item~~ (Delayed, may in v0.3.0 or later)
- [ ] ~~Support images messages~~ (Delayed, may in v0.3.0 or later)

> **Note**
>
> Some plans may be postponed to the v0.3.0 or even later due to actual development progress and difficulty.
